"""Add new violations tracking fields

Revision ID: 251553687c8b
Revises: 9d11326c64ae
Create Date: 2026-01-08 22:15:34.704689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251553687c8b'
down_revision: Union[str, None] = '9d11326c64ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('new_violations_detected', sa.Boolean(), nullable=True))
    op.add_column('inspections', sa.Column('new_violations_count', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('new_violations_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'new_violations_date')
    op.drop_column('inspections', 'new_violations_count')
    op.drop_column('inspections', 'new_violations_detected')
    # ### end Alembic commands ###
