"""add_load_dt_to_inspections

Revision ID: 4bcbb3c3fb36
Revises: 251553687c8b
Create Date: 2026-01-08 23:16:27.543294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcbb3c3fb36'
down_revision: Union[str, None] = '251553687c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('load_dt', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_inspections_load_dt'), 'inspections', ['load_dt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_load_dt'), table_name='inspections')
    op.drop_column('inspections', 'load_dt')
    # ### end Alembic commands ###
