"""Add email, social media, business registration, and violation tracking fields

Revision ID: 9d11326c64ae
Revises: 001
Create Date: 2026-01-08 21:22:47.194949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d11326c64ae'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('year_founded', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('registration_state', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('registered_agent', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('other_addresses', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('services', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('contacted', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('contacted_date', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('contact_notes', sa.Text(), nullable=True))
    op.add_column('inspections', sa.Column('last_violation_check', sa.DateTime(), nullable=True))
    op.add_column('inspections', sa.Column('violation_check_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'violation_check_count')
    op.drop_column('inspections', 'last_violation_check')
    op.drop_column('companies', 'contact_notes')
    op.drop_column('companies', 'contacted_date')
    op.drop_column('companies', 'contacted')
    op.drop_column('companies', 'services')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'other_addresses')
    op.drop_column('companies', 'business_type')
    op.drop_column('companies', 'registered_agent')
    op.drop_column('companies', 'registration_number')
    op.drop_column('companies', 'registration_state')
    op.drop_column('companies', 'year_founded')
    op.drop_column('companies', 'youtube_url')
    op.drop_column('companies', 'instagram_url')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
